"""
Suite de pruebas de la Fase 4: core/storage
===========================================
Cubre persistencia columnar (LanceDB), consultas por clave, borrado,
busqueda vectorial densa, fusion hibrida RRF, resolucion configurable
de la ruta de almacenamiento y politica de embeddings.
"""

import os
import shutil
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from core.storage import (
    DEFAULT_VECTOR_DIM,
    EmbeddingError,
    FastEmbedEmbedder,
    HashEmbedder,
    LanceDBStore,
    OpportunityRecord,
    get_embedder,
    resolve_db_path,
)
from core.storage.lancedb_store import _sql_literal

try:
    import fastembed  # noqa: F401 - solo se comprueba si está instalado
    FASTEMBED_AVAILABLE = True
except ImportError:
    FASTEMBED_AVAILABLE = False


# Embedder ligero y determinista para las pruebas de persistencia:
# mantiene la suite rapida y sin dependencias de red.
TEST_DIM = 64


def _record(rec_id, text, **kwargs):
    return OpportunityRecord(id=rec_id, text=text, **kwargs)


class StoreTestCase(unittest.TestCase):
    """Base con una tabla LanceDB temporal por prueba."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="rir_test_")
        self.addCleanup(shutil.rmtree, self.tmpdir, True)
        self.embedder = HashEmbedder(dim=TEST_DIM)
        self.store = LanceDBStore(db_path=self.tmpdir, embedder=self.embedder)


class TestResolveDbPath(unittest.TestCase):
    """La ruta de almacenamiento debe ser configurable, nunca un hardcode."""

    def setUp(self):
        # patch.dict devuelve el entorno a como estaba, pase lo que pase.
        entorno = mock.patch.dict(os.environ)
        entorno.start()
        self.addCleanup(entorno.stop)
        os.environ.pop("RIR_LANCEDB_PATH", None)

    def test_explicit_argument_wins_over_environment(self):
        os.environ["RIR_LANCEDB_PATH"] = os.path.join("C:", "desde_entorno")
        expected = Path(os.path.join("C:", "explicita"))
        self.assertEqual(resolve_db_path(os.path.join("C:", "explicita")), expected)

    def test_environment_variable_is_honoured(self):
        target = os.path.join("C:", "desde_entorno")
        os.environ["RIR_LANCEDB_PATH"] = target
        self.assertEqual(resolve_db_path(), Path(target))

    def test_fallback_is_relative_to_project_root(self):
        project_root = Path(__file__).resolve().parents[1]
        self.assertEqual(resolve_db_path(), project_root / "data" / "lancedb")

    def test_module_carries_no_absolute_drive_hardcode(self):
        source = (
            Path(__file__).resolve().parents[1] / "core" / "storage" / "lancedb_store.py"
        ).read_text(encoding="utf-8")
        self.assertNotIn("F:" + chr(92) + "reddit_intelligence_radar", source)


class TestSqlLiteral(unittest.TestCase):
    """El escape de literales SQL es la defensa contra la inyeccion."""

    def test_plain_value_is_quoted(self):
        self.assertEqual(_sql_literal("abc123"), "'abc123'")

    def test_single_quote_is_doubled(self):
        self.assertEqual(_sql_literal("x'y"), "'x''y'")

    def test_injection_payload_stays_inside_the_literal(self):
        self.assertEqual(_sql_literal("' OR '1'='1"), "''' OR ''1''=''1'")

    def test_non_string_input_is_rejected(self):
        with self.assertRaises(TypeError):
            _sql_literal(42)


class TestInsertion(StoreTestCase):

    def test_insert_returns_number_of_rows_written(self):
        written = self.store.insert_opportunities([
            _record("a1", "no puedo exportar facturas"),
            _record("b2", "busco alternativa a notion"),
        ])
        self.assertEqual(written, 2)
        self.assertEqual(self.store.count_records(), 2)

    def test_insert_of_empty_batch_is_a_noop(self):
        self.assertEqual(self.store.insert_opportunities([]), 0)
        self.assertEqual(self.store.count_records(), 0)

    def test_missing_vector_is_autogenerated_with_the_configured_dimension(self):
        self.store.insert_opportunities([_record("a1", "texto sin vector")])
        stored = self.store.get_by_id("a1")
        self.assertIsNotNone(stored)
        self.assertEqual(len(stored["vector"]), TEST_DIM)

    def test_optional_fields_are_persisted(self):
        self.store.insert_opportunities([
            _record(
                "a1",
                "pierdo horas con la conciliacion bancaria",
                subreddit="smallbusiness",
                score=42,
                urgency_tier="HIGH",
                opportunity_score=0.87,
                job_statement="conciliar movimientos sin copiar a mano",
                current_solution="excel",
                workaround_detected=True,
            )
        ])
        stored = self.store.get_by_id("a1")
        self.assertEqual(stored["subreddit"], "smallbusiness")
        self.assertEqual(stored["score"], 42)
        self.assertEqual(stored["urgency_tier"], "HIGH")
        self.assertAlmostEqual(stored["opportunity_score"], 0.87, places=6)
        self.assertTrue(stored["workaround_detected"])


class TestSinAutor(StoreTestCase):
    """R9: el nombre de usuario no se guarda en el almacén vectorial."""

    def test_el_registro_no_tiene_autor(self):
        self.assertNotIn("author", OpportunityRecord.model_fields)

    def test_la_tabla_no_tiene_columna_de_autor(self):
        self.assertNotIn("author", self.store._table.schema.names)

    def test_una_tabla_antigua_pierde_la_columna_y_conserva_las_filas(self):
        import lancedb
        import pyarrow as pa

        antiguo = tempfile.mkdtemp(prefix="rir_test_")
        self.addCleanup(shutil.rmtree, antiguo, True)
        esquema = pa.schema([
            pa.field("id", pa.string()), pa.field("text", pa.string()),
            pa.field("author", pa.string()),
            pa.field("vector", pa.list_(pa.float32(), TEST_DIM)),
        ])
        tabla = lancedb.connect(antiguo).create_table(LanceDBStore.TABLE_NAME, schema=esquema)
        tabla.add([{"id": "t3_viejo", "text": "texto antiguo", "author": "u/nombre_real",
                    "vector": [0.1] * TEST_DIM}])

        reabierto = LanceDBStore(db_path=antiguo, embedder=self.embedder)
        self.assertNotIn("author", reabierto._table.schema.names)
        filas = reabierto._table.to_arrow().to_pylist()
        self.assertEqual([f["id"] for f in filas], ["t3_viejo"])
        self.assertNotIn("nombre_real", str(filas))


class TestReopening(StoreTestCase):
    """
    Regresion: `list_tables()` devuelve un ListTablesResponse, no una lista,
    asi que comprobar `nombre in lista` daba siempre falso y el almacen
    intentaba recrear una tabla existente. Reventaba al abrir cualquier
    almacen con datos, que es justo el caso de produccion; los demas tests
    no lo veian porque cada uno estrena directorio.
    """

    def test_an_existing_store_can_be_reopened(self):
        self.store.insert_opportunities([_record("a1", "primer registro")])
        reabierto = LanceDBStore(db_path=self.tmpdir, embedder=self.embedder)
        self.assertEqual(reabierto.count_records(), 1)

    def test_reopening_preserves_the_records(self):
        self.store.insert_opportunities([_record("a1", "texto original")])
        reabierto = LanceDBStore(db_path=self.tmpdir, embedder=self.embedder)
        self.assertEqual(reabierto.get_by_id("a1")["text"], "texto original")

    def test_a_third_open_still_works(self):
        LanceDBStore(db_path=self.tmpdir, embedder=self.embedder)
        tercero = LanceDBStore(db_path=self.tmpdir, embedder=self.embedder)
        self.assertEqual(tercero.count_records(), 0)


class TestGetById(StoreTestCase):

    def setUp(self):
        super().setUp()
        self.store.insert_opportunities([
            _record("a1", "primer registro"),
            _record("b2", "segundo registro"),
        ])

    def test_returns_the_matching_record(self):
        self.assertEqual(self.store.get_by_id("a1")["text"], "primer registro")

    def test_returns_none_for_unknown_id(self):
        self.assertIsNone(self.store.get_by_id("no-existe"))

    def test_injection_payload_matches_nothing(self):
        self.assertIsNone(self.store.get_by_id("' OR '1'='1"))
        self.assertEqual(self.store.count_records(), 2)

    def test_id_containing_a_quote_is_retrievable(self):
        self.store.insert_opportunities([_record("o'brien", "apostrofo legitimo")])
        self.assertEqual(self.store.get_by_id("o'brien")["text"], "apostrofo legitimo")


class TestDeleteById(StoreTestCase):

    def setUp(self):
        super().setUp()
        self.store.insert_opportunities([
            _record("a1", "primer registro"),
            _record("b2", "segundo registro"),
            _record("c3", "tercer registro"),
        ])

    def test_delete_removes_only_the_target(self):
        self.assertTrue(self.store.delete_by_id("b2"))
        self.assertEqual(self.store.count_records(), 2)
        self.assertIsNone(self.store.get_by_id("b2"))
        self.assertIsNotNone(self.store.get_by_id("a1"))

    def test_delete_of_unknown_id_reports_false(self):
        self.assertFalse(self.store.delete_by_id("no-existe"))
        self.assertEqual(self.store.count_records(), 3)

    def test_injection_payload_does_not_wipe_the_table(self):
        self.store.delete_by_id("' OR '1'='1")
        self.assertEqual(self.store.count_records(), 3)

    def test_id_containing_a_quote_is_deletable(self):
        self.store.insert_opportunities([_record("o'brien", "apostrofo legitimo")])
        self.assertTrue(self.store.delete_by_id("o'brien"))
        self.assertIsNone(self.store.get_by_id("o'brien"))

    def test_a_store_failure_reports_false(self):
        with mock.patch.object(self.store._table, "delete", side_effect=OSError("disco")), \
                self.assertLogs("core.storage.lancedb_store", "ERROR"):
            self.assertFalse(self.store.delete_by_id("a1"))

    def test_a_programming_error_is_not_swallowed(self):
        # Un id que no es texto es un fallo de quien llama, no del almacén.
        with self.assertRaises(TypeError):
            self.store.delete_by_id(42)


class TestVectorSearch(StoreTestCase):

    def setUp(self):
        super().setUp()
        self.store.insert_opportunities([
            _record("a1", "exportar facturas a csv", urgency_tier="HIGH",
                    opportunity_score=0.9),
            _record("b2", "alternativa a notion para equipos", urgency_tier="LOW",
                    opportunity_score=0.4),
            _record("c3", "automatizar respuestas de soporte", urgency_tier="HIGH",
                    opportunity_score=0.7),
        ])

    def test_nearest_neighbour_is_the_exact_match(self):
        hits = self.store.search_vector(
            self.embedder.embed_text("exportar facturas a csv"), limit=3
        )
        self.assertEqual(hits[0]["id"], "a1")

    def test_limit_caps_the_result_set(self):
        hits = self.store.search_vector(
            self.embedder.embed_text("cualquier cosa"), limit=2
        )
        self.assertEqual(len(hits), 2)

    def test_sql_filter_restricts_candidates(self):
        hits = self.store.search_vector(
            self.embedder.embed_text("exportar facturas"),
            limit=10,
            filter_sql="urgency_tier = 'HIGH'",
        )
        self.assertEqual({h["id"] for h in hits}, {"a1", "c3"})

    def test_search_text_embeds_the_query_and_finds_the_match(self):
        hits = self.store.search_text("alternativa a notion para equipos", limit=1)
        self.assertEqual(hits[0]["id"], "b2")

    def test_ids_where_returns_only_matching_keys(self):
        self.assertEqual(
            set(self.store.ids_where("opportunity_score >= 0.7")), {"a1", "c3"}
        )

    def test_filter_ids_intersects_candidates_with_the_predicate(self):
        self.assertEqual(
            self.store.filter_ids(["a1", "b2"], "urgency_tier = 'HIGH'"), {"a1"}
        )

    def test_filter_ids_of_an_empty_candidate_set_is_empty(self):
        self.assertEqual(self.store.filter_ids([], "urgency_tier = 'HIGH'"), set())

    def test_filter_ids_without_predicate_returns_the_candidates(self):
        self.assertEqual(self.store.filter_ids(["a1", "b2"], ""), {"a1", "b2"})

    def test_filter_ids_escapes_quotes_in_candidate_keys(self):
        self.store.insert_opportunities([
            _record("o'brien", "apostrofo legitimo", urgency_tier="HIGH")
        ])
        self.assertEqual(
            self.store.filter_ids(["o'brien", "b2"], "urgency_tier = 'HIGH'"),
            {"o'brien"},
        )


class TestEmbeddingPolicy(unittest.TestCase):
    """El hash MD5 es un recurso de emergencia, jamas el camino por defecto."""

    def test_hash_embedder_declares_itself_non_semantic(self):
        self.assertFalse(HashEmbedder(dim=TEST_DIM).is_semantic)

    def test_hash_embedder_produces_unit_norm_vectors(self):
        vec = HashEmbedder(dim=TEST_DIM).embed_text("texto de prueba")
        self.assertEqual(len(vec), TEST_DIM)
        self.assertAlmostEqual(sum(v * v for v in vec) ** 0.5, 1.0, places=5)

    def test_hash_embedder_is_deterministic(self):
        emb = HashEmbedder(dim=TEST_DIM)
        self.assertEqual(emb.embed_text("mismo texto"), emb.embed_text("mismo texto"))

    def test_empty_text_yields_a_zero_vector(self):
        self.assertEqual(HashEmbedder(dim=TEST_DIM).embed_text("   "), [0.0] * TEST_DIM)

    def test_batch_matches_individual_embedding(self):
        emb = HashEmbedder(dim=TEST_DIM)
        batch = emb.embed_batch(["uno", "dos"])
        self.assertEqual(batch, [emb.embed_text("uno"), emb.embed_text("dos")])

    def test_get_embedder_raises_when_no_real_provider_and_no_opt_in(self):
        with self.assertRaises(EmbeddingError):
            get_embedder(allow_hash_fallback=False, _force_unavailable=True)

    def test_hash_fallback_requires_explicit_opt_in(self):
        with self.assertLogs("core.storage.embeddings", level="WARNING") as captured:
            emb = get_embedder(allow_hash_fallback=True, _force_unavailable=True)
        self.assertIsInstance(emb, HashEmbedder)
        self.assertIn("DEGRADADOS", "".join(captured.output))

    def test_default_vector_dim_matches_the_real_provider(self):
        self.assertEqual(DEFAULT_VECTOR_DIM, 384)


@unittest.skipUnless(FASTEMBED_AVAILABLE, "fastembed no esta instalado")
class TestRealEmbeddings(unittest.TestCase):
    """Prueba de que el espacio vectorial ya no es un placebo."""

    @classmethod
    def setUpClass(cls):
        cls.embedder = FastEmbedEmbedder()

    @staticmethod
    def _cosine(a, b):
        return sum(x * y for x, y in zip(a, b))

    def test_provider_declares_itself_semantic(self):
        self.assertTrue(self.embedder.is_semantic)

    def test_dimension_is_384(self):
        self.assertEqual(self.embedder.dim, 384)
        self.assertEqual(len(self.embedder.embed_text("hello world")), 384)

    def test_vectors_are_unit_norm(self):
        vec = self.embedder.embed_text("invoice export is broken")
        self.assertAlmostEqual(sum(v * v for v in vec) ** 0.5, 1.0, places=4)

    def test_paraphrases_are_closer_than_unrelated_text(self):
        anchor = self.embedder.embed_text("I cannot export my invoices to a CSV file")
        paraphrase = self.embedder.embed_text("exporting bills as spreadsheets fails")
        unrelated = self.embedder.embed_text("my cat sleeps on the keyboard all day")

        self.assertGreater(
            self._cosine(anchor, paraphrase), self._cosine(anchor, unrelated)
        )

    def test_hash_embedder_cannot_do_the_same(self):
        """Contraste explicito: el placebo no captura parafrasis."""
        hasher = HashEmbedder(dim=384)
        anchor = hasher.embed_text("I cannot export my invoices to a CSV file")
        paraphrase = hasher.embed_text("exporting bills as spreadsheets fails")
        self.assertLess(self._cosine(anchor, paraphrase), 0.2)


class TestPublicApi(unittest.TestCase):

    def test_package_exports_the_documented_surface(self):
        from core import storage

        for name in (
            "LanceDBStore", "OpportunityRecord", "HashEmbedder", "FastEmbedEmbedder",
            "get_embedder", "resolve_db_path", "EmbeddingError",
            "DEFAULT_VECTOR_DIM",
        ):
            self.assertIn(name, storage.__all__)
            self.assertTrue(hasattr(storage, name))


if __name__ == "__main__":
    unittest.main()
